# Generated by Django 6.0.5 on 2026-06-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
