# Generated by Django 6.0.5 on 2026-06-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0002_alter_user_info_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='cholestrol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='glucose',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='haemoglobin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
