# Generated by Django 6.0.5 on 2026-06-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0003_user_info_cholestrol_user_info_glucose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
