# Generated by Django 6.0.5 on 2026-06-02 08:40

import MIRA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='dob',
            field=models.DateField(validators=[MIRA.models.validate_dob], verbose_name='Date of Birth'),
        ),
    ]
