# Generated by Django 6.0.5 on 2026-06-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0005_alter_user_info_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='cholestrol',
            new_name='cholesterol',
        ),
        migrations.AddField(
            model_name='user_info',
            name='remarks',
            field=models.CharField(null=True),
        ),
    ]
