# Generated by Django 6.0.5 on 2026-06-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0006_rename_cholestrol_user_info_cholesterol_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
