# Generated by Django 6.0.5 on 2026-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0007_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email_add',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
