# Generated by Django 6.0.5 on 2026-06-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIRA', '0008_alter_user_info_email_add_alter_user_info_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='glucose',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
